version: '3.1'

services:
  api:
    image: localhost:8081/repository/docker-repo/api-project:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://marlon:2190835@mongo:27017/nest
    networks:
      - app-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: marlon
      MONGO_INITDB_ROOT_PASSWORD: 2190835
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
