version: '3.1'

services:
  api:
    image: your-nexus-repo/api-project:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGO_URI: mongodb://marlon:2190835@mongo:27017/nest
      RABBITMQ_URI: amqp://marlon:2190835@rabbitmq:5672
    networks:
      - app-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: marlon
      MONGO_INITDB_ROOT_PASSWORD: 2190835
    ports:
      - 27017:27017
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: marlon
      RABBITMQ_DEFAULT_PASS: 2190835
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
